//
//  VigenereTests.swift
//  VigenereTests
//
//  Created by Vitor Demenighi on 15/04/21.
//

import XCTest

@testable import Vigenere

class VigenereTests: XCTestCase {

    var sut: Main!
    
    override func setUp() {
        sut = Main()
    }
    
    override func tearDown() {
        sut = nil
    }

    func testGetFrequency()  {
        let frequency = sut.getFrequency(text: "aaabcc")
        let a_frequency = frequency["a"]
        let b_frequency = frequency["b"]
        let c_frequency = frequency["c"]
        
        XCTAssertEqual(a_frequency, 3)
        XCTAssertEqual(b_frequency, 1)
        XCTAssertEqual(c_frequency, 2)
    }
    
    func testGetCoincidenceIndex() {
        let expetectResult: Double = 0.06352
        
        let myFrequency = sut.getFrequency(text: TestsSeeds.text)
        
        let result = sut.getCoincidenceIndex(frequency: myFrequency)
        
        XCTAssertEqual(result, expetectResult, accuracy: 0.001)
    }
    
    func testGetCoincidenceIndexSubstring() {
        let text = "jxwwjtcwjexbaimgm"
        
        let frequency = sut.getFrequency(text: text)
        
        let result = sut.getCoincidenceIndex(frequency: frequency)
        
        XCTAssertEqual(result, 0.05882, accuracy: 0.001)
    }
    
    func testSplitText() {
        let text = "jakxqswecwmmjbktqmcmlwcxjbnewsxkrboiaobinomljguimh"
        
        let result = sut.splitText(keySize: 3, orignalText: text)
        
        XCTAssertEqual(result[0],"jxwwjtcwjexbaimgm")
        XCTAssertEqual(result[1],"aqembqmcbwkoonluh")
        XCTAssertEqual(result[2],"kscmkmlxnsriboji")
    }
    
    func testDiscoverKeySize() {
        
        let result = sut.discoverKeySize(originalText: TestsSeeds.longText)
        
        XCTAssertEqual(result, 7)
    }
    
    func testVerifyResult() {
        
        let result = sut.verifyResult(0.06351)
        
        XCTAssertTrue(result)
    }
    
    func testCompleteFlow() {
        
        let keySize = sut.discoverKeySize(originalText: TestsSeeds.longText)
        let result = sut.discoveryKeyValue(keySize: keySize, text: TestsSeeds.longText)
        
        
    }
}

class TestsSeeds {
    static var text = "plsual tlroao crqcoc auiser emmoir anstoi ozaend roabio rmrcaa ocsnen idtliu annvdu epranr etqeeu sscepx texrae xemxot ssiedtr"
    
    
    static var longText = "cyyzvmgurwbszxmehacexuzyfgqeoslnuqqpijhpxmoelhaxmhvipcysahyfiyrqvgnwzieilvovyxkuqchmemiaodmasondmmjshnraugihbjueayhbegidmuifawqwjyszhavyfrgqdiavaqrbsfvhugauorddsyingwmlgquawpepiozozsheyeofspelnruezxyqsdmcyymopibetrzufqvxnrqlanyacawqyyyccyqrnrzufqpfbhuhagizcgqxmpecemzgyeccyqihpsdvmtiejqrfylnoxkgrmrfdseihgfqtgrbnrawpiprfpepimzoeugihbcnwfehgsovqhiermqmmmyodkmimrfqrmhcfqgwesjrfpidegfsupxymrgbedexvgueoemrobsxmnvqmgaqinzuxfilnhgvmxiebayeilroxmexupczwomyahqhmwwbbpmqwxnjuhmvynzxmytuqsmfexlnqqwbilvuawmwyqoegarwrdqwmtlvcdmcyygcbvajoarmqqrnrfqzapprfmqmwcagfmfycrgqgaqnbvktaxbrhugawvrbqjugcbgvrawfvquxatyeugrfelfsymzgiefqvysmacbidmabrqwqvgbgmgoymnrawpicawymssmqoomhmfvgmseiufooxgeyftdqmwxruazqvhbrqqaglnhugaimgcpiexcaopeeexhfmvqefnfsedwyvbpirmhvrmqqrnrszxdinnbfsmgiefqrfixraagdenvqmgdimpsoszxcaimqqrnrgataywbgawcyyqihmpegragmfsmnwzhmsmdiqxqignrqqaglnqueosgbiyhakgnqarfvubegexhyaopehefraawrewgcetmvurgfiesmqseeexlrgpsekiisdrawxraagdenvqaweskhoxugilpcuwmgizcmwyehvtqwfeyfraeflyvgyscyycodeawweszxqwyzbmhmtlrxghuguzceefxlvpgxawxbgpigwyfhahmzcnsexqjuphaiexupfqrmrufjuvfyxrgmfesfhhmwyemvbpiyshfhdepemqiyervgnrqkazyebarakueozxuevngfezxyqcetdsaesewawxnrqqaglnqueqqyfqdihmuycdholyfhqvrmyyrcyqxiqcesewszdfsyemdiqnyecfhurtepvgfsyelpodiyruuwexavcnomtbvikwyeahytfmrpimgfmrejieamiesoeshsxyyfbawqmiqiykazyebaijmmgwmqcyyyzmlavurddssvyqwmqpmuewmqqrnrsyjdehnceluwnbfuepslrgzsewifqarfigccdeziifdmwyegqscyqewehqemvcfhagdewvoqsopyeczsfmprgeiygizdditihqwpscyyrareoixnwdvqpctwaugiwnrmhueyfhmzmquvgqqhsanoovqruacetdmpvzqkusmqszeegczszxariccpmmquahqveijbfyeuwnrabspiprfueyzlnoyimexrdqvfylooqwuqgvbqrfimaoahuihgourhidnrmwpmzssdizxyfqxeewyfoymeilvoesdhcqopseguzdarqdyfrqzqvcnhqpawjesbedexbogqrslzwpehifyshezxuzszxawipwmpbsxrfueyxyecnwqvpnraeeguhgmwuqgrruefemqiyedipbzgszexrgavpigqoejuruaoeizeaecewqmlnrqwukonzpepixbgfvufogceeetlrjuwqwkhseidmuzdawemprwesguorgqrawuswsydeggoqwzsmrfqexmmnfmqqelrjapgslrpqrfsondqwmvxrgqvxihgomeogozixeahifgqyeifraqrfsmdiqsuxifsoyxsmqsyszelpvuemfmbzgxmigdiqsewyhgbvurwvdusewyscdeyvuqwoezhitfmhgefrqarexuahqqqrnrhurtegccexaeifcxlawxrbmxgvurgqiexlnbtseezeamhqkiisdragizcbidtygimizsmrdqvoivvoosysozfqkuqyaegifmhuoriuxinizmpexrsmkdehqslepezeozebsxrgeimpahapmmwyerqwfvovraeurxnsylgqynhfvufovomtdsmcsdmpexrrmrmszeozgqwunceigvytwyiztiywfmosyiwmqmmmpogwmwxrrqkqryeoarawabjqvzsmywhvqwwbaaeurayofidvuqccyqrusfmrmsgnwetqvzrwfsysxrzahmqiaodgtmunpesxynnoewuqhfsexmqifvanqexraagdewvohmoxiewawmezvugvmwyacemzzyaquzqpywbagarwrpqqawjecsvqwmbtdepsmriuqbilvcyeetieegiqwnnqqkmgiatuezeupoeszshbgfidvyfsdzmhibtgxgvihapieihtozseigrztezxynccyqwistdigearfmscyyngemexchfqzapobtdezgymozsfilbcekazyebawpigbqdefmwbgridqyahawpixvgesxyifirjugcrbfietueozsejumsdiyhoiwpedhufimiexuowxmpexrjqnmqifamwmrnrgoszzgqsrmzmlbgqrfmxbfqwfvcphaxmpprnqboimfwheyihgsdiexlvqfscyyqoyseekhwbexepeopiysweoommquvbqizxyarqtavxraagdewvogruguzszxqygntdqmtuehuggpuerqkazyebalmhongyeziceoehqgiaqqfqvitchidriqiyeeswvspepiyqotmpyufrujrilrbfiequasuvmwxrobvqgcnfmwdifnseizxlruazqvhnbfieiabjqvzexbgayakiisdrmrnrggtqvcbfmshemfoxpawyhqtirinhhavqkovoqugefdiqvcyyfsveyemfimwrefgoesekiisdrmhifrqzqqfusfspsiesetqmnbsqqoemboxkgqjbrqvavygwdedpbroeymeophavuhuqsayawabjqvzehgsewawczdxieearbfieignbpefelvcehawabjqvzexbgarqwnrqmwaewrbeydeozruvqmnboavukyzrmeggnbfuhmhyesempihbgsshilaopseuoropsayuesfmdegpcysvyftoyqmmmhhupqbwrdfymrxbodyewcnsmxgvkhwmiyuorobvuqyvfmjdquqssshilaceiyehgsyeurxnsyxahunggebylrnmxahifcetmmtrgpeqylbdmiyfieofizluzopsbxuqcrvyemzwjxmwxrhdezwcbfqgarbrqqvmqufcnidehvobsbyfnfuwfsznnqqpilvjmvmeophavuhuqspehshgopipsmtchidruqceiexusfyepiabjqvzskhsyeurypvmqmhyzcovmgcnsqwfegrgyeemaawrmoeiyvqefxlvpgmdicasexqimgipsbelnshmfelhamgarzhgaxatlrxghugcnzosysmrfuemhyzseidzcergqfilzcosyzuycdhujzrfqrfijnfmgmhuhapizwxbbpizsmisusqwnntdqmhytchidrifsdhujzvquppmtrzagaqlvuavmqyhjdeoshfhuxgmivbspqduntgrpeiqceiexuqceyzmxbgpemqyewoemvyicxyajlnboilezbfmqurkhsexushnjqpyihgspseifraqrfsmdiqqmmmpczgavlrfmqbelnoexdehftavyeyfdapuxcpoeiyjuicdhmhyzcovmgcnbayxxczceioyfbamwbelrqqqyicaggjrmwvszxqwjnfmhmvyzsjtxmwncoenefqsfsxeltoevqziyiqweilvobvqgcfcvyzxueztieembpdeehifdtmxsmbdtseixbgeenmifegibvycodedegbsetuvcgcbsbyfnfqeegiaruieigdiqsbvitfqwesmpwqrfmzvqagapfbqaymtlbrggahuewcyqdufsdmmtlvbombefzszxqtlrquwaimgipedempwdggqmgozguemuwexavcpoeugixrhqvymhnfmqaimgonixiwvaqrfsxnrqqaglnqueomlpiywfehpwmwpmzssdizxyfdmvmguqozeatufgmrpsxnegiexiqsavukyzvuwfslvopsekiisdrawxraagdenvqawhigbgcyqimgorvyexruazqvhbgqxqqgbgfvmhinhtsvixhamkdehqsurexuowxmpexrsmwemgpcysmwonrujrymbfmtuhunhdehwxrhahawifdmmlimqoqydsjnbawxipnoeybtldiqhqzyewmqqbcfhuvoeofoehqslqsykqvuysosyqoagmxahifcetmmtrgmwemggoyfqquvbexmfcywpepixbbazavytwyiziggcpeeemaoqwcyybopsbxueoysnvctozseemhgbiuxuerqugiwrffeyihgsoszxlnfmugefdiqvfihqszgueihsxiyihgcqweihpwmppemfcomqhuqseqahyebmwoshusompeuuwexavcnrmjdehnegiqqgrbawpygfsoyxsyfhzefilpsuvmvycinpugurhqqhmmgcmpfilaodiywyzczedgbvoemytyewawqvycinpugufqaqgquessyxelvrmhquongutqvcbrugmebrgbezlurbfvqsjewyiuvirgfenifrquqqrnbdatgpuesyimewpsewahihzfmyslrwzsfipraqrawxregedihgoxihehgoyizxifaupuxuesehqrugidileaeohiyecbfbedxyqceugeyfgqeewipwaymtfrpqieevrgqkqvuyaqrfiidiqxqigfwpsqwinwzhmemesbynpcpoehmegrfugmwhnpapuzcnrqugenbflibvyfwpizxyfrmvqtoozugmxlrnqqavlrfmqmwmngemzexbgayzsykwxmawyrloibxonfyseevrzsmoeifsexmhifizmpsmrourpeuvhmpuejbrqvqqifrudqvkhsbsdxiqomtmvnrcekazyebawbsjhzmvqwzhbogushnayexihbfmvawibfukqqxrdqvfylooqweswvoqwcyufwbidquaszxqwjbrqqawwbbopgmlqoeymlcfhavuekhsmhqqipfmguehbgqrawucfqwqrnnqaqaxyarayypueuajgxoecqqqwgborvyexruazqvhbegieinraysexlnraqmmmsfmkupgnwejmgcyaqrfimhxqmfeupczwfehgseqgxurgbsewcisxizgiahdedempogwmwxrgfeemhtixedjuyhmhqikhwxmnvcbrawfigcceqahyebawmqyhjdiygyehaqahicfqguwiacfeduorrqwpiipcyiahifsoyxsjeseizxyqcuweihgwyizxifbmgushnsefqqxvgfmzgnbgmgfyuzgafdiuridsbeipquhqrnnzbedefusehmviacyicyyyvqwpsifegiawxrhqwfeghaamytyewmpuwgbsasgxlbcdepmwnzuwysnbrastsgraafeiliopsdxyebaxmhidiqiyxiqoeeerurgyspilaoelmygnzmvseufduvmsxrszkdehqsomyihgcpiavxraqhqmhqsbizhyaqueuwnbegizscaruzuhobopugmlvifexhyfszzappvaqrfskhsolqkunqarexcgiuvgqxbgsizilbgyeuwphzsedimqsxsggoeoahqpcewahmwaeozhqdufoehqhyewcyqdurdahqvgnbujqwnnaeizembquipexrqaqukonzurfihfwpepiyhabeudjnfmwqvaeozhqtueopedvynzuwmsurgfieshucmfesliszxqrypsewuxuhasvmrxrsjidgcgcbvqgcfofidignfyeeygnegezxcqopipibbaqreuongumsyuyhaxmpcqopipsmiodieruszdhmixnrqsdeivabidmuyweqaiuqsysovupwmwamlesoszgcywmzqmmnqarpmiccdijgyyzqromuqcbvuqyvfaeafyqwqromuroneeizhbpeyihgoxhawabjqvzsmccbyxelrgmpufyermhqhyqweggwmbsmjmgoyrmhqhyeshsxxufsytdikhsqwfemqimwfihqszguembdbsexufgqqmrcssexmvyzopieslqsywqvcefqqqhcnjqpmzcphavuejbfyvmviqsubmvxrdqvfihpsdeamgcsdmmpcfaatavkhsawqrnvaqrfsxndmdqslqsywgtyewavxmvrfpepiwbaqedtiewytavpvcxizxuzszxqeiospmqrwvoqhqtivgmeosyqioefmpnctenmnbhavzefusmwagcrrmhqevfcxyfegrbfipswvzmwqkoarmhmwwnieeehycsdxgvvncqrgqyeopeeslnrugmpcfaaratiqsdmmluisdyywctbmppsnrabsyecftavymxnjqpqquvgmqqeuqcdtmvubuazqvhbdatgpueraugiiaoeguqyahahqklhdawuvlrqaromfvohiuwhnamweexndatgpubegiqwnrgsvgtifgqjavgraesnvyhammxpofcayesvesgqmfufsdimpgrbfivymgoqgaqinfpsdfyyzugawirormzhizohixuorztiehiboetqgnbsmvukcqslmzuorpdezxuisxhgqufsuxmvyywsmawunrqqaglnquefilqszxdsxrguyyguaqdsurwhfmzqpjbfcyqgizorvmuornmhmgivbtidihgsmsekiisdrawjbdgpmvyfscyqpbrghiyhusfmkyihgoaioshgbgeeyvfhuxgmiqcbspilrdavaynecxepswbaaietcewfspiahsdvmmhgfmremarbfipslnrugmpcfaasbilvuatmvunsexmfcywpepixnrqqaglnqueeilgozxaquvcdugehgcyeuwzeoosejiesyseqyvcehqvycfqwesynegixpurgbiomyqsdepmwnzuwyskhszseejcodioiwbaaraqyqszmtmfvgysmrueqtmeqirgqqqpbnbfieenucvimmhqozsqrwbbfvayzeamhqkiisdrauoroeefmmswliewyasyizgiahdedtieqqvfsjbweugihbhqqayneomwbmlncpirmhvrmugihbgqnmexrgavpigcsdqmryahqeehyzcovmgcngqroshgfmqdiuyaqrfihrgfeejlzoehavuqwoexmmzcgqurczwsscyyngrelsmpwxpmvwbbexmrnraqrfiyahdimzcqoqeyslgsqrfvybgyeximpczwfmnhquszeyfrawssprfzsehyzcovmxcpceicyybgqqnelnoyhqefpozedscqsmpcyyacpsymhvcmfexlnqfsxlyfdmvqgcnrqwfmhnraebyfisdmeeiqcbspilccxmfmwbvafnimcszwmuoregezhihatsyigngbmdeufsdpuzlrccyqvynzyizxyqseiveozobedxyqcsshilacaugiuqsysovupwmptiwbboipigngqwfejnffizsabjqvzsystqgfmpncgeysmngbexepeoehqnuzsewfijuszugignwzifvuagovqzybwzhuzcqiaugijqsmqarnbodsyecbfzyyilbrqjdeazszxawjbzuxugifbgqeqiahqkazyebmvavyfhaiygyehawysgrbfseygpodeoxyeszidkcpczsgxlbgmeexopwmrayneceeoejnquhmhynrymzmmgfmxuzuacgxdsmnsxscyyaquezsogfawmtifgqhawfbumvqwwbayyzwyntmgupcqopipiifobvazyvhmvzygswytdenvqatqvgvhfiyeozvaqqqnesbedtyycelaqvecehawmriezuwcavawqhcewsmxsmasexqsoaocyqpfrgqrfmxbamwqqnbrasoembceugiyfharmjcysuvmwytiqqmhcesospsmpvqjqwxhamtdsprbuizgcncghmsogfmuginbamqagizamrpsxntavmgiyzqgfmpnotmexiewmhmwyysuiegiavqguhufonmpsidiqwukhvtugmsuyodkmqyahahawostdesmipcysyicbrqexguaodyyedhgfepmmgfufgmiqcbspilccxmfmwbvmyyeprfpepiceooebmnnzuwmsjbzuxugupcysmgucwfexmmncqgarizwoepimgodieyfgoaesmigopecyyyzmsqqjeseedmiccxmfmwbczsewivbrpgihgsmrmsgnwehqqipfmxuguqcyyzhibibixsgrbawmtiahmhmgizcfexsmrgfepsmhbuhawizsxlavyksytxsxngukzmzvqmscyygsyspmlrwfspipbhmvmpfvchsfsozoyidguaqueosgbcmpssxbcgsegyesmiesjbrqvbelnegiyquvgesgfyeqmtuxuyweedtiewewarifsdxqqyewpepiustuvyeldiqseyzsfmkusoawhidwuyhavzemrbmtdenvqmenemrbmxgvuyrgqmzyermhqmlnhkvmrhvourrifvnyizxycodezwnraawoshusompsxrgafqnirgfeekorfdeehissghmpcfaatapcgwosqeyeopsequeegilexbgqpqmnbfmietuesoiqwnnfyyuxiyczkqhifsgjuqmhdbszluzcetavgdiqiexyiwomawofqqtfmprzpioslesoseyjcczlmqifegiawostdesmihbuzqvmnzolqkuhapmmezhbogushnfqqbilssuxmpcosdhmhynvktaxbrgqmdvynzuwmzyydavcyynzufqvxnrqmytfvqmeoshpcdvqrwvoqhmhurgfeawuzpugusmbgqsetuehuhawmhfsiymgzspmmxuzszxqrufggeehcywsizgcngpiosfusuxmqufgqjawmrdawemprzcyqsmhtrvmkcbdatgpuetgrogcbbmweiyzdqvricgoxmnilqopizsnrfueysmasxpqygnumvmrnvopibvitfqwesjbfcyqwuowpscyuahasqwjvfuxaticixedigessvmexisdwawneozwrslzoqwcyybddssvyfgawomyahujugivbpmoebnaqwyswrffeatjbgusqrnesmhqqipfmgueyngomqrwvomsyimzcfiytidiqehmxnrawssprfzsehyzcovmxcpcetqpuvbexmfcywpepiyqsesdhyzqarfrongzsejumrgzuhuerawqyzhhgvaihbgpiubufsyietyeozepijbrqvysmnzoezelccdqqmiqsxpqwubfpiyimrugvmruasoiewuewmwmsjecsvqwmbdavaynecxepsufzuiehuuwexavcnrarawyksytxsmqiyemhgvfmzqpjecetqvcqopiesvessmyihfdapuxcpcefqqxvjqvesmrofsbtifhawmlcfhavuezhbpmmvcnaqrfiuewexaglnhmhudmgfmyewuzouwxeltofizxugwhepilruqrqvubbmgushnzcyqluqcuweiwhzawfigndbediwvraizxlrbesxeltcbpmriqcyeduornpibsgooxwqxcisewqtiqwpsyehgsdwqgizqqvfitnbawmwmrugvmvcniytdsmcsdsrynhfaqmwmbpgqmjlzopissprfzscyyfsbediwvoniytihqagaquqsysovupwmifsxnjuecyufwzstejbffysyymwzxqpfvuqrfiyfwzgqvidiqrapuzszxqemhocyqhunrqqaglnquemxbrbuizwypivsehcngrsdeggcoydxifsmsmflvuahmuonzmedxyngomqrwvoqeblcycesblcnzmrmvuziyehiarhmsfsgnfmzupbbgmrailngqraygnodmexipfmgueyyshepembpdimwlhwzeehozoayfvunfuwfsweoommqovhaqmmmesexdmwgoawqwjyszhavyfegimxneomqmenuszeexiqcakqrcbcdmsmhnzpsyyhqcqrfswvjupuwuqcmpuqyahmzmqmrdqpmmgccemahyvabsexifrqwmtcrrmhawmbpdigqgvztedhypwpepimioewmpfngqsesjrfmvusmuoniuwkhsesnexvfqgahycvuhuemyshezxueoysbelgvqraryeoywuqjyseieglnjawawyfhmhawoawpsewiqcevmvifsjiytfbgqqcyynrqqaglnqueqsjecsvqwmbjaeewipwmhawyzqmtuxoycqwbiwvoxzqvyzcescyyaodimpcqopimhyzcovmgcnbmeyilvqmqmmhrhagmryfhqtarnbiyepemdiqwfimzouwsvuisehmwxraagdewvoeeewongdixeyfqaqmuorgfseswvoxgduorrqwpiizcyizxiracyqempzmweimyonsdmifoegarkhwexqqiccpidliqsbixsmfsgwyehqofedmifsjidgyycqqbviisuxahudiqpxemzseqmwwyoewqwmhdbsquoropiysweoommtlrhqrpilpcdvukceourvymgwmipimvugexhuqscyqliwseipruqwexdmvhwahmvcdiqdmixrgfefihgofmhejbrqvuelrggpfelnggemrcdiupmsozobedxyqsexmhyfhdsqwypczwfehgsyizxycsxsoshfiysqtueocyqimfobedxyfsdibviqileziwrgeedmizozxqvurbqvsmuqceqafcfrmtdsxhqasdeyfhqwnemrwmqeijewzgutuyaqrfihnzuzdiwbbosdvyaquediwbbtioikhsawysvvgcyqruucdebvyfszxqirpwfeyebhamruhuqsmsfvuooxlaiubzmfavjnfmvqwofquxmvuewcyqduracymrnvrmhqwyzddiovyfqqrfimbrqrmxoeslemeleoexmvcatmpxmprzyizxynrqwukonzpepihnddsbvcnruwfvcoiuspimfodmcyymomxfvcoiqebvifdqvuhuqspseimgopseyhvrawmsueravpefhqfebifnjuhmwioiykazyebaiyuorhahmwuffqwfvcpsegailpwfmhemfsdipytramsymhvaaeeyuoszirmwnddsetyewpepivngqmmwyvbfiuvuzszxqrufozxuhuqspsoshgfmgfsyaoqwfevvzuhmhyqobvatlvspepijewhepeucfuqqmlnwzwfvozszxaemrugrpelrqaqbihfopseywpsewarupczgavlrbommyhvjqveefrluwfigqimwoenruavuemqsysnmmqwliqbcfhqqehongesnecatxyqrwvopeeuonseefliwseibhycfahgdcesdibviqilmdeyacdqquonbfmpexrrqqmxyewmierypsewmvcbgeynwcfhqromuroagarzbffspebhamruhuqsatdmgrwdsecmgsyeahuywhvqgiaqavdihpwmsecmgsyeeiahwpszeuzsdmoexbbavfiifssyzhipczwuwnrsyhmvwbbfeemgczqwyihgspeeyugodireierurmvcnhmvqjuswjepennzhiltiegqrtslrgqugmnnhuzawyoczwyemvabsexuncevqguyquxdehgsetqpucfuwasocsxsolcpcfirscqsexqyfgwysecmgsyecyyofaxayuzodehmfuceebvifdqvuhuqspsbilfcnsemhpoeifilzwzefehgccymrnbbapaihfwzemircsdmqrwvoesysmscdepsmnqaropovfcyqxiqomwagcrrmhqhyismhatnnfgqayihhdsecmgsyeesvcszepiwnfpebihhfuezecaozmairnaurqqifoetdsjbguietlvbombeyfbmwgenuseiqqjewyiuviycsedrifsbvazudiqepigbqdeomugszlmymnraiywyhddshicgcpsbsxrfcyqgiaegmexihjqvpexregiawostdesmihbuzqvmnzeifslacgenemrrgqmzyermhqmlnhkvmrhvoeisyhqcmijtlrgespignwzizsmtchidrifrqqaglnhugawnraeirslzopshilqopiuvufcxmselpvueeexzwzmexlnbpsawhruagusmqcqwfexbsywqyjechiuxirbfvqrmaceyxxczcegurwbszxmehacenfmpraawpscfsjiytfbgpifclnbzmmwxrgfeqwjrquigqundammrxbgqrmzcbzqromubbajmziefqexeihhdeqvctwzhaewbfdybsyzgkwfigndapuxcpcqzuzyaratavyfhqqqmirgfeesfvumvolcngsshilaoyiywyhsjgxymvjatdsprwfsmwweweiewipwmieiypczsymwngcyqhierurmvcbztiewopqqhqqjecheyrifibidevhbpezxyzszxqqufegezhinrqqaglnquefmprfoszwytiuhakiisdrmvlroxqqrnrqaqahyrgbidelqoevqjieamwbsmfwhiuwxngurexcgiuieixbgosexozsegxelbegizsjbrqvpickodhqkiisdrmvyzgqynihrtugusufzqmeuorfqwgpnnfahqwmrbazaimgopseilbrqrmxoeslemqiqwrmoelnzuzdiwbbosdvyaqueqrintdsgbuecbsdimfsreoxibgysnmmqobvahopcpedmkhsleqrnesgqmgiaqavdihpwmhqwyatdimhuriyvqkczszhqimpfmzuhirluwfigrgfepsmvbfidqxvceiexmrugvahuccewqhufggeexyefmwatlbddmqxuewaggnifpqretiqsyqmrbfsdijtlbddmmhifsyfqryswomatoozugaribwytawnbhmqnighamtmvwrzxepsmrifvmfuyvaifsxnjuezsiogfezxyngyyuxuffqwfvcpseugiducvieszsfqspmlrwfspijecbvuixnrqexicnwzhmhyvlayqwnvagpafufhmrfijnfmefslaodebtygsompeifmexqquqoxmhvypczgavlrbommuorbmzqvxnrqtqvnhfneaxlnpmptsykqxyurxbobpqfyqomtdsjewmspsmsfggfsmzozxqrxbourhelvohixqyahqrmqcfsdmmquvbqwgwnrbfecyyuomtqrufrgeegugsssdmufrqqafcfgafmmhszgizgcnrawcyurgbsewcisxeoshfsdzmsynisqqrnbrmvuuornmexmpesoszgiefqromuroqwovuiwpsyemqsreoxirgfiewsfhqqmwmbtgrpegrbfexqyahqmsyurgmpuzlrqarosleszguewesayagucwfexmmzccyqriqwrjqvyrgeizgcnzyizxyqoqwovuiwpsauorbawqwnbaawfvuaragxelnaqrfiuffqzaporgesomurgoszxyzdavmryngzioimfodmaquahqvmejecbvueiqcejdywgcegaqiesosytyagmhaxlnpmptsyccdmewizseqarypsewmvcbhmqnigrgfenifrqqvmgiaqavdihpwmwafozoneeixrxgwfmuaopmexlvpgmawyewmtmvuqseietyeodhqxiqcatdsaesewawyndapuxcpoeiysmgfmweicaqmtmdxrfqwapprfqwfijecnpqqubqarfvuphahqzyfsdwmrnbgqqpypvrmqmwuysuugilrugpmswbbfvmgnbfqhgdcaraeaqcawysmewbqaidgcgwhepembquipexrsxihelraawmsgnluqaemcfafmfcywpepimqcegarneooxawczaavmimrwzngwnbgavmioeszyzgcnfuepivbasvmhinhahmejbzuxugudiqrajifgqhaqcaopebslhauhqefqsvyexcnbqqehycchmhiiucyiyhcmcqzmrarztseewewrmoelgipsmsykqxyempbrqwqrpbzhmyihgcpedmkhslemfxvqmvpskhszstsgratepignwehukhbdavuwmbdqreskhseibsliszxgvungurexcgiuieuorhqiytietuqzslzoxmeelnqarosleszguewbbpylmlramyytydiqraezecgbmqyahahmtlbrggaruqofidigbgmpmqyahmvfigbgmtarnnraexkoagpsezcpwawqtyewssehuqsysovupwmugmxvbpibvifwseysmnwzzqwnvumspsmfsgwqpyzszxawxrtdecyymoqtdswhfmvqqifrqtammngoszgfhgqwcyyqotmpipraawfmlnf"
}


